services:
  dotnet-api:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION_STRING=redis:6379
      - POSTGRES_CONNECTION_STRING=Host=postgres;Port=5432;Database=todoapp;Username=postgres;Password=Lapka
    depends_on:
      - redis
      - postgres

  angular-client:
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      - NG_APP_API_URL=http://localhost:8080/api

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lapka
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
    driver: bridge
